"""Track B -- SEO (Linchpin 3.0 plan section 8). ``crawl_audit`` (S1 technical
SEO audit checks, PR-22). ``schema_gen``/``feeds``/``llms_txt`` (S2 schema and
feed generation from a client's own catalog, PR-23). Later PRs add
``pdp_writer`` (S3) and ``geo_probe`` (S5) alongside them.
"""

from __future__ import annotations

from .crawl_audit import (
    BROKEN_INTERNAL_LINK,
    DUPLICATE_CONTENT,
    DUPLICATE_META_DESCRIPTION,
    DUPLICATE_TITLE,
    ISSUE_TYPES,
    MALFORMED_STRUCTURED_DATA,
    MISSING_ALT_TEXT,
    MISSING_CANONICAL,
    MISSING_META_DESCRIPTION,
    MISSING_STRUCTURED_DATA,
    MISSING_TITLE,
    ROBOTS_TXT_MISSING,
    ROBOTS_TXT_SUSPICIOUS,
    SITEMAP_MISSING,
    SITEMAP_SUSPICIOUS,
    CrawledPage,
    Finding,
    ImageRef,
    RobotsTxtCheck,
    SitemapCheck,
    check_robots_txt,
    check_sitemap_xml,
    find_broken_internal_links,
    find_duplicate_content,
    find_duplicate_meta_descriptions,
    find_duplicate_titles,
    find_missing_alt_text,
    find_missing_canonical,
    find_missing_meta_descriptions,
    find_missing_titles,
    find_structured_data_issues,
    robots_and_sitemap_findings,
    run_checks,
)
from .feeds import (
    FEED_GENERATOR,
    FeedItemResult,
    GenericJsonFeedReport,
    MerchantFeedReport,
    build_generic_json_feed,
    build_merchant_feed_xml,
    missing_required_feed_fields,
    write_excluded_csv,
    write_generic_json_feed,
    write_merchant_feed_xml,
)
from .llms_txt import (
    DEFAULT_SECTION,
    FOOTER_LINE,
    LlmsPage,
    LlmsTxtReport,
    SiteInfo,
    build_llms_txt,
    catalog_to_llms_pages,
    generate_llms_txt,
    is_valid_llms_txt,
    missing_required_llms_fields,
    validate_llms_txt,
    write_llms_txt,
)
from .schema_gen import (
    SCHEMA_ORG_CONTEXT,
    VALID_AVAILABILITY,
    VALID_CONDITION,
    CatalogItem,
    CatalogJsonLdReport,
    ExcludedCatalogItem,
    GeneratedProduct,
    build_product_jsonld,
    catalog_to_jsonld,
    derive_availability,
    is_valid_product_jsonld,
    missing_required_fields,
    normalize_availability_token,
    normalize_condition_token,
    validate_product_jsonld,
    write_catalog_jsonld,
)

__all__ = [
    "BROKEN_INTERNAL_LINK",
    "DUPLICATE_CONTENT",
    "DUPLICATE_META_DESCRIPTION",
    "DUPLICATE_TITLE",
    "ISSUE_TYPES",
    "MALFORMED_STRUCTURED_DATA",
    "MISSING_ALT_TEXT",
    "MISSING_CANONICAL",
    "MISSING_META_DESCRIPTION",
    "MISSING_STRUCTURED_DATA",
    "MISSING_TITLE",
    "ROBOTS_TXT_MISSING",
    "ROBOTS_TXT_SUSPICIOUS",
    "SITEMAP_MISSING",
    "SITEMAP_SUSPICIOUS",
    "CrawledPage",
    "Finding",
    "ImageRef",
    "RobotsTxtCheck",
    "SitemapCheck",
    "check_robots_txt",
    "check_sitemap_xml",
    "find_broken_internal_links",
    "find_duplicate_content",
    "find_duplicate_meta_descriptions",
    "find_duplicate_titles",
    "find_missing_alt_text",
    "find_missing_canonical",
    "find_missing_meta_descriptions",
    "find_missing_titles",
    "find_structured_data_issues",
    "robots_and_sitemap_findings",
    "run_checks",
    # schema_gen (S2)
    "SCHEMA_ORG_CONTEXT",
    "VALID_AVAILABILITY",
    "VALID_CONDITION",
    "CatalogItem",
    "CatalogJsonLdReport",
    "ExcludedCatalogItem",
    "GeneratedProduct",
    "build_product_jsonld",
    "catalog_to_jsonld",
    "derive_availability",
    "is_valid_product_jsonld",
    "missing_required_fields",
    "normalize_availability_token",
    "normalize_condition_token",
    "validate_product_jsonld",
    "write_catalog_jsonld",
    # feeds (S2)
    "FEED_GENERATOR",
    "FeedItemResult",
    "GenericJsonFeedReport",
    "MerchantFeedReport",
    "build_generic_json_feed",
    "build_merchant_feed_xml",
    "missing_required_feed_fields",
    "write_excluded_csv",
    "write_generic_json_feed",
    "write_merchant_feed_xml",
    # llms_txt (S2)
    "DEFAULT_SECTION",
    "FOOTER_LINE",
    "LlmsPage",
    "LlmsTxtReport",
    "SiteInfo",
    "build_llms_txt",
    "catalog_to_llms_pages",
    "generate_llms_txt",
    "is_valid_llms_txt",
    "missing_required_llms_fields",
    "validate_llms_txt",
    "write_llms_txt",
]
