"""S2 ``llms.txt`` generation (Linchpin 3.0 PR-23, plan section 8 "Track B --
SEO", S2 row: ``llms_txt.py``) -- a plain-text summary of a client's key
pages for AI crawlers, per the emerging llms.txt convention
(https://llmstxt.org): an H1 site name, a blockquote one-line summary, an
optional free-text context paragraph, and one or more ``## Section``
headers each listing markdown links with a one-line description.

Reuses ``schema_gen.CatalogItem``/``ExcludedCatalogItem`` for the SAME
catalog-row shape the other two S2 modules consume (Golden Rule 5, DRY --
one product-catalog input type for the whole S2 capability) --
``catalog_to_llms_pages`` turns a catalog into one llms.txt entry per
product PAGE, using the same required-field / exclude-with-reason pattern
as ``schema_gen``/``feeds`` (title + url required; a SKU missing either is
excluded and reported, never silently dropped -- Golden Rule 14). Unlike
``feeds.missing_required_feed_fields``, price/currency/availability are NOT
required here -- an llms.txt entry is a navigational pointer ("here is a
page and what it's about"), not a transactable offer; when price+currency
ARE present they enrich the one-line description, but their absence does
not exclude the page.

**Provenance (Golden Rule 7):** every line in the generated text traces to a
named ``CatalogItem`` column -- ``title`` becomes the link text, ``url`` the
link target, and ``description`` (or, failing that, ``price``+``currency``,
or failing that ``title`` alone) becomes the one-line summary (see
``_page_description``). This is client-authored data, so -- exactly as in
``schema_gen.py`` -- no acquisition-tier/confidence pair is attached; see
that module's docstring for the full distinction between this PR's
column-trace provenance and ``pricing_intel``'s acquisition-tier provenance
for externally-observed data.

**Kern attribution:** unlike the JSON-LD in ``schema_gen.py`` (which must
stay strictly schema.org-compliant, with no third-party watermark), an
llms.txt file is plain free text the SITE ITSELF publishes about itself to
AI crawlers -- a short "Generated by Kern" footer line here is the same kind
of honest, standard practice as a static-site generator's own attribution
comment, not a pollution of structured data. See :data:`FOOTER_LINE`.

No network I/O (HARD RULE) -- pure text generation from an already-loaded
``CatalogItem`` sequence, plus a local file write (matches ``src/export.py``
's own "write to disk from src/" precedent).
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from src.seo.schema_gen import CatalogItem, ExcludedCatalogItem

DEFAULT_SECTION = "Products"
FOOTER_LINE = "Generated by Kern (SEO schema & feed module)."


@dataclass(frozen=True)
class SiteInfo:
    """The site-level identity block (H1 + blockquote + optional context)."""

    name: str
    summary: str
    context: str | None = None
    homepage_url: str | None = None


@dataclass(frozen=True)
class LlmsPage:
    """One ``## Section`` list entry: ``- [title](url): description``."""

    product_id: str
    title: str
    url: str
    description: str
    section: str = DEFAULT_SECTION


@dataclass(frozen=True)
class LlmsTxtReport:
    text: str
    pages: tuple[LlmsPage, ...]
    excluded: tuple[ExcludedCatalogItem, ...]
    n_pages: int
    n_excluded: int
    summary: str


def missing_required_llms_fields(item: CatalogItem) -> list[str]:
    """A page needs at least a name and a link to be listed -- see module
    docstring for why price/currency/availability are NOT required here
    (unlike ``feeds.missing_required_feed_fields``)."""
    missing: list[str] = []
    if not item.product_id or not item.product_id.strip():
        missing.append("product_id")
    if not item.title or not item.title.strip():
        missing.append("title")
    if not item.url or not item.url.strip():
        missing.append("url")
    return missing


def _one_line(text: str) -> str:
    """Collapse a possibly-multi-line description to one line -- an llms.txt
    list entry is a single markdown list item, and an embedded newline would
    silently break it into what a parser reads as multiple entries."""
    return " ".join(text.split())


def _page_description(item: CatalogItem) -> str:
    """Golden Rule 7: every fallback here still traces to a named catalog
    column, in priority order -- never a fabricated sentence."""
    if item.description and item.description.strip():
        return _one_line(item.description)
    if item.price is not None and item.price > 0 and item.currency and item.currency.strip():
        return f"{item.title} -- {item.price:.2f} {item.currency}"
    return item.title  # last resort: still the catalog's own title column


def catalog_to_llms_pages(
    items: Sequence[CatalogItem], *, section: str = DEFAULT_SECTION
) -> tuple[list[LlmsPage], list[ExcludedCatalogItem]]:
    """Turn a catalog into ``(pages, excluded)`` -- every input row lands in
    exactly one of the two lists (Golden Rule 14)."""
    pages: list[LlmsPage] = []
    excluded: list[ExcludedCatalogItem] = []
    for item in items:
        pid = item.product_id if item.product_id and item.product_id.strip() else "<missing product_id>"
        missing = missing_required_llms_fields(item)
        if missing:
            excluded.append(ExcludedCatalogItem(pid, tuple(missing)))
            continue
        pages.append(
            LlmsPage(
                product_id=item.product_id, title=_one_line(item.title), url=item.url,
                description=_page_description(item), section=section,
            )
        )
    return pages, excluded


def generate_llms_txt(site: SiteInfo, pages: Sequence[LlmsPage]) -> str:
    """Render an llms.txt document: H1 site name, blockquote summary,
    optional context paragraph, then one ``## Section`` per distinct
    ``page.section`` value (first-seen order), each listing its pages as
    markdown links, followed by :data:`FOOTER_LINE`."""
    lines: list[str] = [f"# {site.name}", "", f"> {_one_line(site.summary)}"]
    if site.context and site.context.strip():
        lines += ["", site.context.strip()]

    sections: dict[str, list[LlmsPage]] = {}
    for p in pages:
        sections.setdefault(p.section, []).append(p)

    for section_name, section_pages in sections.items():
        lines += ["", f"## {section_name}"]
        for p in section_pages:
            lines.append(f"- [{p.title}]({p.url}): {p.description}")

    lines += ["", "---", FOOTER_LINE]
    return "\n".join(lines) + "\n"


def build_llms_txt(
    site: SiteInfo, items: Sequence[CatalogItem], *, section: str = DEFAULT_SECTION
) -> LlmsTxtReport:
    """The batch entry point: catalog -> pages/excluded -> rendered text."""
    pages, excluded = catalog_to_llms_pages(items, section=section)
    text = generate_llms_txt(site, pages)
    summary = (
        f"llms.txt: {len(pages)} page(s) listed under '{site.name}', {len(excluded)} SKU(s) excluded "
        "for missing required field(s)."
    )
    return LlmsTxtReport(
        text=text, pages=tuple(pages), excluded=tuple(excluded),
        n_pages=len(pages), n_excluded=len(excluded), summary=summary,
    )


def validate_llms_txt(text: str) -> list[str]:
    """Lightweight STRUCTURAL check (not an external validator call, matching
    ``schema_gen.validate_product_jsonld``'s own scope): a valid UTF-8-
    encodable string, an H1 site-name line, a blockquote summary line, and
    -- when the document has any page entries at all -- at least one
    ``## Section`` header and one markdown list-item link. Empty list =
    valid."""
    issues: list[str] = []
    if not isinstance(text, str):
        return ["llms.txt content must be a string"]
    try:
        text.encode("utf-8")
    except UnicodeEncodeError as exc:  # pragma: no cover -- a Python str is always UTF-8-encodable
        issues.append(f"content is not valid UTF-8 text: {exc}")

    lines = text.splitlines()
    if not lines or not lines[0].startswith("# "):
        issues.append("missing an H1 site-name line ('# Name') as the first line")
    if not any(line.startswith("> ") for line in lines):
        issues.append("missing a blockquote summary line ('> ...')")

    has_section = any(line.startswith("## ") for line in lines)
    has_list_item = any(line.startswith("- [") for line in lines)
    if has_section != has_list_item:
        issues.append("a '## Section' header must be paired with at least one '- [title](url): ...' entry")

    return issues


def is_valid_llms_txt(text: str) -> bool:
    return not validate_llms_txt(text)


def write_llms_txt(text: str, out_path: str | Path) -> Path:
    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return path
