"""S2 schema.org JSON-LD generation (Linchpin 3.0 PR-23, plan section 8
"Track B -- SEO", S2 row: ``schema_gen.py`` -- "simetria con el titan:
nosotros LEEMOS JSON-LD de competidores; al cliente le GENERAMOS el suyo").

This module is the MIRROR IMAGE of ``src/pricing_intel/acquire/structured.py``
(PR-11): that module READS arbitrary, uncontrolled JSON-LD off a competitor's
already-fetched PDP HTML -- many possible shapes, extractor-tiered, provenance-
tagged because the data came from somewhere we do not control. This module
WRITES one clean, generator-controlled Product/Offer JSON-LD document per SKU
FROM the client's own catalog -- there is no "extraction" here, only
"authoring" a known, chosen shape. No network I/O (HARD RULE): everything
below is a pure function over an already-loaded ``CatalogItem`` sequence; the
result is either returned as data or written to a LOCAL path (never fetched
or posted anywhere), matching ``src/export.py``'s own "write to disk from
src/" precedent (``src/pricing_intel``'s network I/O lives in its
``acquire/`` subpackage, not in ``models.py``/``extract.py`` -- same split
applied here: this module never imports ``httpx``/``advertools``/etc.).

**Considered reusing ``ProductMetadata`` (structured.py) for this module's
OUTPUT, per the PR instruction to weigh it -- decided NOT to.** Its shape is
input-parsing-shaped: ``json_ld_offers`` is a tuple of *raw, arbitrary* dicts
(zero or more Offer nodes actually found on a page, of unknown origin), and
its provenance fields (``json_ld_source``, ``structured_source_version``)
answer "which extractor engine parsed this, and did it work" -- a question
that only makes sense for data we did not author ourselves. Forcing a
self-generated document through that shape would mean inventing a
placeholder ``json_ld_source="self_generated"`` that answers no real
question and blurs the extraction-vs-generation line Golden Rule 7 draws.
This module's output type (:class:`GeneratedProduct`) is deliberately a
different, smaller shape: ONE finished JSON-LD ``dict`` (literally what a
``<script type="application/ld+json">`` tag needs) plus a ``source_fields``
map tracing every field back to the exact ``CatalogItem`` column that
produced it.

**Golden Rule 7 note (provenance, client-authored data):** ``CompetitorOffer``
(``src/pricing_intel/models.py``) carries ``acquisition_tier`` +
``extractor``/``extractor_version`` + ``extraction_confidence`` because that
data was OBSERVED from a system we do not control and could be wrong, stale,
or mis-parsed. Nothing in THIS module is observed -- every field in a
generated document is copied, unmodified, from a column the client supplied
in their own catalog. The acquisition-tier/confidence pair from pricing_intel
does not fit here and is deliberately NOT attached to this module's output;
provenance for client-authored data instead means tracing each generated
JSON-LD field back to its source catalog column (:class:`GeneratedProduct`
.source_fields`` does exactly this). A future reader should not assume the
two provenance styles are interchangeable -- they answer different questions
("can I trust what I observed" vs. "which of the client's own fields did
this come from").

**Column-naming convention (reuse, not a third naming scheme):**
``product_id`` matches ``jobs/intake.py``'s canonical demand-history column
AND ``src/state/system_state.py``'s "stock"/"prices_own" domain column names,
verbatim. ``price``/``currency`` match the "prices_own" domain's own column
names, verbatim. ``on_hand`` matches the "stock" domain's own column name,
verbatim (used only to DERIVE ``availability`` when the caller does not
supply one explicitly -- see :func:`derive_availability`). ``title``/``url``/
``description``/``image_url``/``brand``/``gtin``/``mpn``/``condition`` have
no existing canonical name anywhere in this repo (neither intake nor state
track PDP copy/media) -- these are new to this module, and are named after
their nearest schema.org property in spirit (not literally, since schema.org
uses camelCase and this repo uses snake_case column names throughout).

**Availability/condition token form:** this module emits the FULL
``https://schema.org/InStock``-style URI (schema.org's own recommended form
for markup meant to be actually embedded and validated), unlike
``pricing_intel``'s ``extract.py``, which tolerantly normalizes messy
real-world competitor markup down to three bare tokens
(``models.AVAILABILITY_VALUES``). Different jobs: that module reads
whatever a THIRD PARTY's page happens to say; this module AUTHORS markup
that must be strictly compliant.

**No Kern watermark inside the JSON-LD itself.** schema.org structured data
describes the CLIENT's product to search engines and must not be polluted
with third-party tool attribution -- a "generated by Kern" property on a
``Product``/``Offer`` node is not a recognized schema.org property and could
confuse a strict downstream validator. Kern's attribution lives in the
surrounding artifacts this PR's OTHER two modules generate instead (an RSS
``<generator>`` tag in ``feeds.py``'s Merchant feed / a ``generated_by``
key in its generic JSON feed; a footer line in ``llms_txt.py``'s output) --
exactly where a client-facing artifact ABOUT the generation process (not a
piece of the client's own product data) is the right place for it.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from src.client_profile import slugify_client_id
from src.export import write_summary_csv

SCHEMA_ORG_CONTEXT = "https://schema.org"

# Practical subset of schema.org's ItemAvailability enumeration (the full
# enum also has InStoreOnly/OnlineOnly/Reserved/SoldOut/PreSale -- omitted
# here because they are not commerce-actionable distinctions this module's
# two input signals (an explicit override, or on_hand > 0) can ever produce;
# a caller needing one of those can still pass it as an explicit
# CatalogItem.availability override in its full-URI or bare-token form, it
# just won't be one of the six this module actively derives/documents).
SCHEMA_AVAILABILITY_TOKENS = (
    "InStock", "OutOfStock", "PreOrder", "BackOrder", "LimitedAvailability", "Discontinued",
)
VALID_AVAILABILITY = tuple(f"{SCHEMA_ORG_CONTEXT}/{t}" for t in SCHEMA_AVAILABILITY_TOKENS)

SCHEMA_CONDITION_TOKENS = ("NewCondition", "UsedCondition", "RefurbishedCondition", "DamagedCondition")
VALID_CONDITION = tuple(f"{SCHEMA_ORG_CONTEXT}/{t}" for t in SCHEMA_CONDITION_TOKENS)

_ISO4217_RE = re.compile(r"^[A-Z]{3}$")

_AVAILABILITY_ALIASES: dict[str, str] = {
    "instock": "InStock", "in_stock": "InStock", "available": "InStock",
    "outofstock": "OutOfStock", "out_of_stock": "OutOfStock", "unavailable": "OutOfStock",
    "soldout": "OutOfStock", "sold_out": "OutOfStock",
    "preorder": "PreOrder", "pre_order": "PreOrder",
    "backorder": "BackOrder", "back_order": "BackOrder",
    "limitedavailability": "LimitedAvailability", "limited": "LimitedAvailability",
    "limited_availability": "LimitedAvailability",
    "discontinued": "Discontinued",
}

_CONDITION_ALIASES: dict[str, str] = {
    "new": "NewCondition",
    "used": "UsedCondition",
    "refurbished": "RefurbishedCondition",
    "damaged": "DamagedCondition",
}


@dataclass(frozen=True)
class CatalogItem:
    """One row of a client's own product catalog -- the source data this
    module turns into schema.org Product/Offer JSON-LD. See the module
    docstring's "column-naming convention" section for which fields reuse an
    existing canonical name (``product_id``/``price``/``currency``/
    ``on_hand``) versus which are new to this module."""

    product_id: str
    title: str | None = None
    price: float | None = None
    currency: str | None = None
    url: str | None = None
    description: str | None = None
    image_url: str | None = None
    brand: str | None = None
    gtin: str | None = None
    mpn: str | None = None
    on_hand: float | None = None
    availability: str | None = None  # explicit override; else derived from on_hand (see derive_availability)
    condition: str | None = None


@dataclass(frozen=True)
class GeneratedProduct:
    """One SKU's finished JSON-LD document, plus its provenance trace."""

    product_id: str
    json_ld: dict
    source_fields: dict[str, str]  # json-ld path -> CatalogItem column (Golden Rule 7)


@dataclass(frozen=True)
class ExcludedCatalogItem:
    """A catalog row that could not produce valid output -- reported, never
    silently dropped (Golden Rule 14). Reused verbatim by ``feeds.py`` and
    ``llms_txt.py`` so the same underlying gap is reported identically
    across all three S2 outputs."""

    product_id: str
    reasons: tuple[str, ...]


@dataclass(frozen=True)
class CatalogJsonLdReport:
    generated: tuple[GeneratedProduct, ...]
    excluded: tuple[ExcludedCatalogItem, ...]
    n_generated: int
    n_excluded: int
    summary: str


def normalize_availability_token(raw: str) -> str | None:
    """Map a caller-supplied availability spelling (a common alias, a bare
    schema.org token, or a full ``https://schema.org/...`` URI) to one of
    :data:`SCHEMA_AVAILABILITY_TOKENS`. Returns ``None`` for anything not
    recognized -- never guessed."""
    key = raw.strip().lower().replace("-", "_").replace(" ", "_")
    if key in _AVAILABILITY_ALIASES:
        return _AVAILABILITY_ALIASES[key]
    bare = raw.strip().rsplit("/", 1)[-1]
    return bare if bare in SCHEMA_AVAILABILITY_TOKENS else None


def normalize_condition_token(raw: str | None) -> str | None:
    """Map a caller-supplied condition spelling to one of
    :data:`SCHEMA_CONDITION_TOKENS`, or ``None`` if ``raw`` is empty/
    unrecognized. ``condition`` is optional everywhere in this module's
    output (see module docstring -- never fabricate a condition the catalog
    did not state)."""
    if not raw or not raw.strip():
        return None
    bare = raw.strip().rsplit("/", 1)[-1]
    if bare in SCHEMA_CONDITION_TOKENS:
        return bare
    key = raw.strip().lower().replace("-", "_").replace(" ", "_")
    return _CONDITION_ALIASES.get(key)


def derive_availability(item: CatalogItem) -> tuple[str | None, str]:
    """Returns ``(bare schema.org token or None, source note)``. An explicit
    ``item.availability`` always wins when it normalizes to a recognized
    token; otherwise falls back to ``item.on_hand`` (matches ``src.state``'s
    "stock" domain column, verbatim): ``on_hand > 0`` -> InStock, else
    OutOfStock. Returns ``(None, reason)`` when neither signal is usable --
    this module never guesses availability (Golden Rule 7)."""
    if item.availability is not None and item.availability.strip():
        token = normalize_availability_token(item.availability)
        if token is not None:
            return token, "availability"
        return None, f"CatalogItem.availability={item.availability!r} is not a recognized value"
    if item.on_hand is not None:
        token = "InStock" if item.on_hand > 0 else "OutOfStock"
        return token, "on_hand"
    return None, "neither an explicit availability nor an on_hand stock signal was supplied"


def missing_required_fields(item: CatalogItem) -> list[str]:
    """Which of this module's required catalog columns ``item`` is missing,
    checked BEFORE attempting to build JSON-LD so a caller gets one clear,
    citable reason list instead of a generic validator failure downstream.
    Empty list = ready to build. Required: ``product_id``, ``title``,
    ``price`` (> 0), ``currency``, and an availability signal (see
    :func:`derive_availability`)."""
    missing: list[str] = []
    if not item.product_id or not item.product_id.strip():
        missing.append("product_id")
    if not item.title or not item.title.strip():
        missing.append("title")
    if item.price is None or item.price <= 0:
        missing.append("price")
    if not item.currency or not item.currency.strip():
        missing.append("currency")
    availability_token, availability_note = derive_availability(item)
    if availability_token is None:
        missing.append(f"availability ({availability_note})")
    return missing


def build_product_jsonld(item: CatalogItem) -> tuple[dict, dict[str, str]]:
    """Build ONE Product/Offer JSON-LD document for ``item``. Raises
    ``ValueError`` naming what is missing if ``missing_required_fields(item)``
    is non-empty -- this function never emits a partially-fabricated
    document (QA instruction: a row missing a required field must be
    reported/excluded, never silently emitted as invalid JSON-LD).

    Returns ``(json_ld_document, source_fields)`` -- see
    :class:`GeneratedProduct` for what ``source_fields`` means.
    """
    missing = missing_required_fields(item)
    if missing:
        raise ValueError(f"cannot build JSON-LD for product_id={item.product_id!r}: missing {missing}")

    availability_token, availability_source = derive_availability(item)
    assert availability_token is not None  # guaranteed by the missing-fields check above

    doc: dict = {
        "@context": SCHEMA_ORG_CONTEXT,
        "@type": "Product",
        "name": item.title,
        "sku": item.product_id,
    }
    source_fields: dict[str, str] = {"name": "title", "sku": "product_id"}

    if item.description and item.description.strip():
        doc["description"] = item.description
        source_fields["description"] = "description"
    if item.image_url and item.image_url.strip():
        doc["image"] = item.image_url
        source_fields["image"] = "image_url"
    if item.brand and item.brand.strip():
        doc["brand"] = {"@type": "Brand", "name": item.brand}
        source_fields["brand.name"] = "brand"
    if item.gtin and item.gtin.strip():
        doc["gtin"] = item.gtin
        source_fields["gtin"] = "gtin"
    if item.mpn and item.mpn.strip():
        doc["mpn"] = item.mpn
        source_fields["mpn"] = "mpn"

    offers: dict = {
        "@type": "Offer",
        "priceCurrency": item.currency,
        "price": round(float(item.price), 2),
        "availability": f"{SCHEMA_ORG_CONTEXT}/{availability_token}",
    }
    source_fields["offers.priceCurrency"] = "currency"
    source_fields["offers.price"] = "price"
    source_fields["offers.availability"] = availability_source

    if item.url and item.url.strip():
        offers["url"] = item.url
        source_fields["offers.url"] = "url"

    condition_token = normalize_condition_token(item.condition)
    if condition_token is not None:
        offers["itemCondition"] = f"{SCHEMA_ORG_CONTEXT}/{condition_token}"
        source_fields["offers.itemCondition"] = "condition"

    doc["offers"] = offers
    return doc, source_fields


def validate_product_jsonld(doc: object) -> list[str]:
    """Lightweight STRUCTURAL check that ``doc`` satisfies the schema.org
    Product/Offer shape this module promises (required fields present,
    correct types) -- not a call to an external validator service (e.g.
    Google's Rich Results Test), matching the PR's own instruction. Empty
    list = valid. Deliberately reusable on ANY JSON-LD dict, not only ones
    this module built (e.g. a caller could point it at a hand-authored
    document too)."""
    issues: list[str] = []
    if not isinstance(doc, dict):
        return ["document is not a JSON object (dict)"]

    if doc.get("@context") != SCHEMA_ORG_CONTEXT:
        issues.append(f"@context must be {SCHEMA_ORG_CONTEXT!r}")
    if doc.get("@type") != "Product":
        issues.append("@type must be 'Product'")

    name = doc.get("name")
    if not isinstance(name, str) or not name.strip():
        issues.append("name is required and must be a non-empty string")
    sku = doc.get("sku")
    if not isinstance(sku, str) or not sku.strip():
        issues.append("sku is required and must be a non-empty string")

    offers = doc.get("offers")
    if not isinstance(offers, dict):
        issues.append("offers is required and must be a JSON object")
        return issues  # nothing further to check without an offers object

    if offers.get("@type") != "Offer":
        issues.append("offers.@type must be 'Offer'")

    price = offers.get("price")
    if isinstance(price, bool) or not isinstance(price, (int, float)) or price <= 0:
        issues.append("offers.price is required and must be a positive number")

    currency = offers.get("priceCurrency")
    if not isinstance(currency, str) or not _ISO4217_RE.match(currency):
        issues.append("offers.priceCurrency is required and must be a 3-letter ISO 4217 code")

    availability = offers.get("availability")
    if availability not in VALID_AVAILABILITY:
        issues.append(f"offers.availability must be one of {VALID_AVAILABILITY}")

    url = offers.get("url")
    if url is not None and (not isinstance(url, str) or not url.strip()):
        issues.append("offers.url, when present, must be a non-empty string")

    condition = offers.get("itemCondition")
    if condition is not None and condition not in VALID_CONDITION:
        issues.append(f"offers.itemCondition, when present, must be one of {VALID_CONDITION}")

    return issues


def is_valid_product_jsonld(doc: object) -> bool:
    return not validate_product_jsonld(doc)


def catalog_to_jsonld(items: Sequence[CatalogItem]) -> CatalogJsonLdReport:
    """The batch entry point: one :class:`GeneratedProduct` per SKU that has
    every required field AND whose built document passes
    :func:`validate_product_jsonld`, one :class:`ExcludedCatalogItem` per SKU
    that does not (Golden Rule 14 -- every input row is accounted for in
    exactly one of the two output lists, never dropped)."""
    generated: list[GeneratedProduct] = []
    excluded: list[ExcludedCatalogItem] = []

    for item in items:
        pid = item.product_id if item.product_id and item.product_id.strip() else "<missing product_id>"
        missing = missing_required_fields(item)
        if missing:
            excluded.append(ExcludedCatalogItem(pid, tuple(missing)))
            continue

        doc, source_fields = build_product_jsonld(item)
        issues = validate_product_jsonld(doc)
        if issues:
            # Should not happen when missing_required_fields passed, but a
            # validator disagreement is still an exclusion, never a shrug
            # (QA instruction: never silently emit invalid JSON-LD).
            excluded.append(
                ExcludedCatalogItem(pid, tuple(f"generated document failed validation: {i}" for i in issues))
            )
            continue

        generated.append(GeneratedProduct(pid, doc, source_fields))

    summary = (
        f"schema_gen: {len(generated)} SKU(s) produced valid Product/Offer JSON-LD, "
        f"{len(excluded)} excluded for missing/invalid required field(s)."
    )
    return CatalogJsonLdReport(
        generated=tuple(generated), excluded=tuple(excluded),
        n_generated=len(generated), n_excluded=len(excluded), summary=summary,
    )


def _safe_filename(product_id: str) -> str:
    """Filesystem-safe filename stem for a per-SKU JSON-LD file. Reuses
    ``src.client_profile.slugify_client_id``'s transliterate-then-collapse
    logic (DRY -- the same "stable, filesystem-safe key from a display
    string" need, applied to a product_id instead of a client name), with a
    hash-based fallback for the rare product_id that slugifies to nothing
    (all non-Latin-script or all-punctuation)."""
    try:
        return slugify_client_id(product_id)
    except ValueError:
        return "sku-" + hashlib.sha256(product_id.encode("utf-8")).hexdigest()[:16]


def write_catalog_jsonld(report: CatalogJsonLdReport, out_dir: str | Path) -> dict[str, Path]:
    """Writes one ``<slug>.jsonld.json`` file per generated SKU (ready to
    paste verbatim into a ``<script type="application/ld+json">`` tag), one
    combined ``catalog_jsonld.json`` array for review, and a
    ``schema_gen_excluded.csv`` so an exclusion is never silent (Golden Rule
    14). Local file writes only -- no network I/O (module docstring)."""
    d = Path(out_dir)
    d.mkdir(parents=True, exist_ok=True)
    per_sku_dir = d / "jsonld"
    per_sku_dir.mkdir(parents=True, exist_ok=True)

    written: dict[str, Path] = {}
    for g in report.generated:
        path = per_sku_dir / f"{_safe_filename(g.product_id)}.jsonld.json"
        path.write_text(json.dumps(g.json_ld, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        written[f"jsonld:{g.product_id}"] = path

    combined_path = d / "catalog_jsonld.json"
    combined_path.write_text(
        json.dumps([g.json_ld for g in report.generated], indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    written["combined"] = combined_path

    excluded_path = d / "schema_gen_excluded.csv"
    if report.excluded:
        rows = [{"product_id": e.product_id, "reasons": "; ".join(e.reasons)} for e in report.excluded]
        written["excluded_csv"] = write_summary_csv(rows, excluded_path)
    else:
        pd.DataFrame(columns=["product_id", "reasons"]).to_csv(excluded_path, index=False)
        written["excluded_csv"] = excluded_path

    return written
